services:
  db:
    image: mariadb:latest
    restart: always
    container_name: nextcloud-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${NEXTCLOUD_DB_PORT}:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nextcloud-app
    ports:
      - "${NEXTCLOUD_HTTP_PORT}:80"
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
