services:
  db:
    image: mariadb:latest
    restart: always
    container_name: nextcloud-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nextcloud-app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: nextcloud_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
